declare const _default: {
    TG_API_ID: number;
    TG_API_HASH: string;
    TG_BOT_TOKEN: string;
    DATA_DIR: string;
    CACHE_DIR: string;
    LOG_LEVEL: "info" | "warn" | "error" | "trace" | "debug" | "fatal" | "mark" | "off";
    LOG_FILE_LEVEL: "info" | "warn" | "error" | "trace" | "debug" | "fatal" | "mark" | "off";
    LOG_FILE: string;
    OICQ_LOG_LEVEL: "info" | "warn" | "error" | "trace" | "debug" | "fatal" | "mark" | "off";
    TG_LOG_LEVEL: "info" | "warn" | "error" | "debug" | "none";
    TG_CONNECTION: "websocket" | "tcp";
    TG_USE_TEST_DC: boolean;
    IPV6: boolean;
    TGS_TO_GIF: string;
    DISABLE_FILE_UPLOAD_TIP: boolean;
    ENABLE_FEATURE_MANAGER: boolean;
    LISTEN_PORT: number;
    ERROR_REPORTING: boolean;
    SHOW_NICKNAME_MODE: string;
    FORWARD_MODE: string;
    COMMAND_REPLY_BOTH_SIDES: boolean;
    ENABLE_AUTO_RECALL: boolean;
    ENABLE_OFFLINE_NOTIFICATION: boolean;
    OFFLINE_NOTIFICATION_COOLDOWN: number;
    REPO: string;
    REF: string;
    COMMIT: string;
    FFMPEG_PATH?: string | undefined;
    FFPROBE_PATH?: string | undefined;
    NAPCAT_WS_URL?: string | undefined;
    SIGN_API?: string | undefined;
    SIGN_VER?: string | undefined;
    TG_INITIAL_DCID?: number | undefined;
    TG_INITIAL_SERVER?: string | undefined;
    TG_MEDIA_TTL_SECONDS?: number | undefined;
    ADMIN_QQ?: number | undefined;
    ADMIN_TG?: number | undefined;
    PROXY_IP?: string | undefined;
    PROXY_PORT?: number | undefined;
    PROXY_USERNAME?: string | undefined;
    PROXY_PASSWORD?: string | undefined;
    IMAGE_SUMMARY?: string | undefined;
    ADMIN_TOKEN?: string | undefined;
    UI_PATH?: string | undefined;
    UI_PROXY?: string | undefined;
    WEB_ENDPOINT?: string | undefined;
    RICH_HEADER_VERSION?: string | undefined;
    INTERNAL_WEB_ENDPOINT?: string | undefined;
};
export default _default;
