export { env, db } from '@napgram/infra-kit';
import type { IInstance } from './runtime-types';
export declare const Instance: {
    readonly instances: IInstance[];
};
export type Instance = IInstance;
export { sentry } from '@napgram/infra-kit';
export { getLogger } from '@napgram/infra-kit';
export { ApiResponse } from '@napgram/infra-kit';
export { ErrorResponses, registerDualRoute } from '@napgram/infra-kit';
export { getMimeType } from '@napgram/infra-kit';
export declare const TEMP_PATH: string;
export { TTLCache } from '@napgram/infra-kit';
export { convert } from '@napgram/media-kit';
export { convert as default } from '@napgram/media-kit';
export { formatDate } from '@napgram/infra-kit';
export { groupInfoCache } from '@napgram/infra-kit';
export type { default as TelegramClient } from '@napgram/telegram-client';
export { hashing as hashingUtils, DurationParser } from '@napgram/infra-kit';
export * from './runtime-types';
export { getGlobalRuntime, tryGetGlobalRuntime } from './runtime-holder';
